### ISSUE TITLE
String misinterpreted as an int results in error on E2015

### ISSUE THREAD

**Issue by jongogogo** [aws-cloudformation/cfn-python-lint#1062]
```
cfn-lint --version
cfn-lint 0.19.1
```

*Description of issue.*
The following template
```
Parameters:
  CentralAccountId:
    Default: 112233445566
    MaxLength: 12
    MinLength: 12
    Type: String
```
result in the error:
```
E0002 Unknown exception while processing rule E2015: object of type 'int' has no len()
application-account-initial-setup.yaml:1:1
```

It is solved by putting quotes on the default value. However it is valid to not putting the quotes.
