### ISSUE TITLE
Bug: E0002 Unknown exception while processing rule E3003: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by direvus** [aws-cloudformation/cfn-python-lint#1088]
*cfn-lint version: (`cfn-lint --version`)*

cfn-lint 0.23.1

*Description of issue.*

E0002 Unknown exception while processing rule E3003: 'NoneType' object is not iterable

The template is in fact valid, I'm able to deploy it to CloudFormation without errors.  I'm not entirely sure why this error is appearing, and I haven't had the time to isolate down a minimal test template yet.  I can say that the error may be caused by a AWS::Transfer::User resource -- if I comment out this resource, the error vanishes just as mysteriously as it appeared.  Could be a problem with the spec for this resource type?

**Comment by chuckmeyer** [comment]
Hi, @direvus -- it's possible, but I'm not sure what in the spec would break E3003 (required properties).

Do you mind posting the template or the snippet for the AWS::Transfer::User that is breaking?

**Comment by direvus** [comment]
Hi @chuckmeyer, I have had a bit more of a play with this and it seems to be related to using a !Ref as a member in SshPublicKeys.  The below snippet triggers the error in $SUBJECT, but if I replace `!Ref SSHPublicKey` with a literal string, the error goes away.

```
---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy resources for the SFTP managed service'

Parameters:
  SSHPublicKey:
    Type: String
    Description: 'SSH public key of the SFTP transfer user'

Resources:
  SFTPDTRFUser:
    Type: AWS::Transfer::User
    Properties:
      UserName: test
      ServerId: s-123456
      Role: arn:aws:iam:etc
      SshPublicKeys:
        - !Ref SSHPublicKey
      Tags:
        - Key: Issue
          Value: https://github.com/aws-cloudformation/cfn-python-lint/issues/1088
```
