### ISSUE TITLE
E1022 Fn::Join must use a list - fails with CloudFormation Custom Resource

### ISSUE THREAD

**Issue by kgutwin** [aws-cloudformation/cfn-python-lint#1127]
*cfn-lint version: 0.21.4*

E1022 helpfully checks Fn::Join arguments for their type as a list; however, it is not able to recognize CloudFormation Custom Resource outputs as possible lists.

The following template launches successfully:
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  CustomResourceFn:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: index.handler
      Runtime: python3.7
      InlineCode: |
        import cfnresponse
        def handler(event, context):
          outputs = {'ListOutput': ['joe', 'jill', 'jane', 'jim']}
          return cfnresponse.send(event, context, "SUCCESS", outputs)

  CustomResource:
    Type: "Custom::Resource"
    Properties:
      ServiceToken: !GetAtt CustomResourceFn.Arn

  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      Tags:
        - Key: BucketUsers
          Value: !Join [":", !GetAtt CustomResource.ListOutput]
```

However, it raises the following error:
```
E1022 Fn::Join must use a list at Resources/Bucket/Properties/Tags/0/Value/Fn::Join
cfn/core/E1022.yml:25:11
```
