### ISSUE TITLE
Ignore-checks doesn't work for E000*

### ISSUE THREAD

**Issue by jeffmacdonald** [aws-cloudformation/cfn-python-lint#1133]
*cfn-lint version: 0.22.3

*Ignore Checks isn't working*

Template: https://gist.github.com/jeffmacdonald/cbbdd8cc3a049f89dfb4a17991ca1afa

I am getting the following error:

```
E0000 Expecting value
templates/ssh-jump-host.yaml:1:1
```

When I run `pipenv run cfn-lint --ignore-checks=E0000 templates/ssh-jump-host.yaml`

The fun part is, I have I have errors in other templates (E2521) and I am able to ignore those just fine... it seems it's specifically E0000 that doesn't get ignored.

**Comment by kddejong** [comment]
Agreed some of the E0000-E0005 checks may not be properly skipped when being configured to ignore them.  We'll have to add some logic in for some of these generic rules.

**Comment by tkeeber** [comment]
Is this still an issue? I'm trying to ignore a check on a specific resource which uses a Transform function. But it is not getting ignore when i use the following; 

```
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
          - E0001
```

**Comment by stlava** [comment]
Seeing the same issue with `E0000`.

**Comment by raphael-riel** [comment]
Idem here. `E0001` won't be ignored.
Tried ignoring in Metadata on Resource, top-level node, and in .cfnlintrc file.

**Comment by mrpatrick** [comment]
This still does not work for me running cfn-lint version `0.51.0` on a SAM template file:

```bash
cfn-lint --ignore-checks=E0000 -t template.yaml
E0000 Duplicate resource found "TaskType" (line 200)
template.yaml:200:11

E0000 Duplicate resource found "TaskType" (line 203)
template.yaml:203:11
```

**Comment by PatMyron** [comment]
@mrpatrick can you try a space instead of `=`?

**Comment by mrpatrick** [comment]
@PatMyron yes, I tried that too - also tried `--ignore-bad-template`

```bash
cfn-lint --ignore-checks E0000 -t template.yaml
E0000 Duplicate resource found "TaskType" (line 200)
template.yaml:200:11

E0000 Duplicate resource found "TaskType" (line 203)
template.yaml:203:11

cfn-lint --ignore-bad-template --ignore-checks E0000 -t template.yaml
E0000 Duplicate resource found "TaskType" (line 200)
template.yaml:200:11

E0000 Duplicate resource found "TaskType" (line 203)
template.yaml:203:11
```

**Comment by PatMyron** [comment]
@mrpatrick do you feel comfortable sharing the template?

**Comment by mrpatrick** [comment]
@PatMyron Here is the relevant code snippet (redacted much of the resource which isn't relevant):

```yaml
  AppFlow:
    DependsOn: "SomeBucketPolicy"
    Type: AWS::AppFlow::Flow
    Properties:
      Tasks:
        - TaskType: Filter
          SourceFields:
            - Email
          ConnectorOperator:
            Salesforce: PROJECTION
        - TaskType: Map
          SourceFields:
            - Email
          TaskProperties:
            - Key: SOURCE_DATA_TYPE
              Value: string
            - Key: DESTINATION_DATA_TYPE
              Value: string
          DestinationField: Email
          ConnectorOperator:
            Salesforce: NO_OP
        - TaskType: Map
          SourceFields:
            - Some_Thing__c
          TaskType: Map
          TaskProperties:
            - Key: SOURCE_DATA_TYPE
              Value: string
            - Key: DESTINATION_DATA_TYPE
              Value: string
          DestinationField: Some_Thing__c
          ConnectorOperator:
            Salesforce: NO_OP
        - TaskType: Map
          SourceFields:
            - Role__c
          TaskType: Map
          TaskProperties:
            - Key: SOURCE_DATA_TYPE
              Value: string
            - Key: DESTINATION_DATA_TYPE
              Value: string
          DestinationField: Role__c
          ConnectorOperator:
            Salesforce: NO_OP
      TriggerConfig:
        TriggerType: Event
```

The issue is the the `TaskType: Map` appears twice for the last 2 tasks.  cnf-lint (correctly) throws 30000 (**this is a bug with my code**).  I didn't notice it until cfn-lint called it out, however, since cloudformation didn't complain (It actually works fine in cloudformation), I wanted to ignore the check, which doesn't appear to work (see above post).
