### ISSUE TITLE
ApiKeyRequired not allowed in Auth section of AWS::Serverless::Api resource

### ISSUE THREAD

**Issue by RadicalDev** [aws-cloudformation/cfn-python-lint#1159]
*cfn-lint version: 0.24.4*

*CFN lint complains about ApiKeyRequired being specified in the Auth section of AWS::Serverless::Api resources.*

According to [this documentation](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api-auth-object) as well as the [Example: Defining API Keys](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-controlling-access-to-apis.html) section of the tutorials, ApiKeyRequired is a supported item in the Auth section. 

cfn-lint, however, is complaining about its presence with the error message:
*E0001 Error transforming template: Resource with id [Api] is invalid. Invalid value for 'Auth' property*

Example template that cfn-lint 0.24.4 complains about:
```yaml
AWSTemplateFormatVersion: 2010-09-09

Transform: 'AWS::Serverless-2016-10-31'

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      EndpointConfiguration: EDGE
      TracingEnabled: true
      Auth:
        ApiKeyRequired: true
```

Incidentally, it doesn't seem possible to ignore this error, either.
