### ISSUE TITLE
W7001 Mapping used in sar location not found

### ISSUE THREAD

**Issue by austinbyers** [aws-cloudformation/cfn-python-lint#1179]
*cfn-lint version: 0.24.6*

Given this CloudFormation template:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Mappings:
  Alarms:
    SemanticVersion:
      Value: 1.0.0

Resources:
  MyApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-west-1:000000000000:applications/myapp
        SemanticVersion: !FindInMap [Alarms, SemanticVersion, Value]
```

`cfn-lint` gives `W7001 Mapping 'Alarms' is defined but not used`

This is valid CloudFormation - `FindInMap` and `Ref` are (the only) allowed intrinsic functions for the Location of a `Serverless::Application`
