### ISSUE TITLE
Warning not ignored with pre-commit hook

### ISSUE THREAD

**Issue by jia2** [aws-cloudformation/cfn-python-lint#1196]
*cfn-lint version: 0.25*
*Python: 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32*
*pre-commit: 1.17.0*
*Description of issue.*

I have below in my `.pre-commit-config.yaml` in my git repository

```yaml
repos:
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.25.0 # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        name: AWS CloudFormation Linter
        files: cfn_templates/.*\.(yml|yaml)$
```

When I run pre-commit, I got a warning:
```
AWS CloudFormation Linter................................................Failed
hookid: cfn-python-lint

W1020 Fn::Sub isn't needed because there are no variables at Resources/KafkaLaunchConfig/Metadata/AWS::CloudFormation::Init/configureKafka/files//opt/kafka/bin/kafka-start.sh/content/Fn::Sub
cfn_templates/kafka_kafkacluster.yaml:244:29
```
I have already put this section in my cloudformation template [https://gist.github.com/jia2/d68e4534a88d58df0f9c24b1d7d056f8]:

```yaml
Metadata:
    cfn-lint:
        config:
            regions:
                - eu-central-1
            ignore_checks:
                - W1020
```
But I still get the warning. When I run cfn-lint standaone to validate this template, then the warning will not be displayed. 

How can I get the validation work with pre-commit? Is there a way to specify ignore checks in `.pre-commit-config.yaml`?

**Comment by kddejong** [comment]
Interesting.  I'll take a look.  Thanks for the detail.

**Comment by kddejong** [comment]
I'm having troubles replicating this.  This template will appropriately skip error W1020 for me.  How many other yaml/yml/json files do you have in that repo?

Our entry point is the same as the command line.
https://github.com/aws-cloudformation/cfn-python-lint/blob/master/.pre-commit-hooks.yaml#L3

```
---
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W1020
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Sub "10.0.0.0/24"
```
