### ISSUE TITLE
`AllocationStrategy` for `SpotFleetRequestConfigData` missing one of three options

### ISSUE THREAD

**Issue by rirze** [aws-cloudformation/cfn-python-lint#1199]
*cfn-lint version: (`cfn-lint --version`)*
```
$ cfn-lint --version
cfn-lint 0.25.1
```
*Description of issue.*

According to the Cloudformation docs for [spotFleetRequestData](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata.html), `AllocationStrategy` can be one of three values: `capacityOptimized` | `diversified` | `lowestPrice`. However, `cfn-lint` throws this error when using `capacityOptimized`:

```
$ cfn-lint genericstack.yaml 
E3030 You must specify a valid value for AllocationStrategy (capacityOptimized).
Valid values are ["diversified", "lowestPrice"]
```

An example code sample is:
```yaml
  spotFleet:
    Type: 'AWS::EC2::SpotFleet'
    Properties:
      SpotFleetRequestConfigData:
        IamFleetRole: !GetAtt spotFleetRole.Arn
        AllocationStrategy: capacityOptimized
        TargetCapacity: 1
        ValidFrom: '2019-11-12T22:41:53Z'
        ValidUntil: '2020-11-12T22:41:53Z'
        TerminateInstancesWithExpiration: true
        Type: maintain
        LaunchTemplateConfigs:
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref launchTemplate
              Version: !GetAtt launchTemplate.LatestVersionNumber

```

This seems like a simple resource update somewhere to update-- if it's simple enough, I'd like to try my hand at it.
