### ISSUE TITLE
Parameter only used in Metadata flagged

### ISSUE THREAD

**Issue by wjvanroosmalen** [aws-cloudformation/cfn-python-lint#1233]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.25.5

*Description of issue.*
incorrect error, mentioning a parameter that is not used while it is used

*Additional info
```
  SourceEventTagFilter:
    Type: String
.....
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Parameters:
      - SourceEventTagFilter
      Label:
        default: Event source filtering
```

It seems that it does not see the resource when used as a parameter
