### ISSUE TITLE
E8001 not allowing `!Condition`s

### ISSUE THREAD

**Issue by jonathanmorley** [aws-cloudformation/cfn-python-lint#1245]
*cfn-lint version: (`0.25.7`)*

*Description of issue.*

Please provide as much information as possible:
* Template linting issues:
  * The expanded E8001 check in 0.25.7 does not allow for top-level `!Condition`s. 

Sample:

```
---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Conditions
Parameters:
  EnableGeoBlocking:
    Type: String
Conditions:
  EnableGeoBlocking: !Equals [ !Ref EnableGeoBlocking, "true" ]
  EnableGeoBlockingAlias: !Condition EnableGeoBlocking
Resources:
  Topic:
    Condition: EnableGeoBlockingAlias
    Type: AWS::SNS::Topic
```
