### ISSUE TITLE
Missing Support for ForwardConfig in AWS::ElasticLoadBalancingV2::ListenerRule

### ISSUE THREAD

**Issue by MattGirolami** [aws-cloudformation/cfn-python-lint#1251]
*cfn-lint version: (`cfn-lint 0.26.0`)*

*Description of issue.*
Receive a rule failure when using a ForwardConfig in a Listener Rule to configure weighted target group traffic routing. I believe the spec file is missing the ForwardConfig option.  

E3002 Invalid Property Resources/ListenerRule1/Properties/Actions/0/ForwardConfig  

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.

```
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  TargetGroup1:
    Type: String
  TargetGroup2:
    Type: String
  Listener:
    Type: String
Resources:
  ListenerRule1:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref 'TargetGroup1'
                Weight: 1
              - TargetGroupArn: !Ref 'TargetGroup2'
                Weight: 1
      Conditions:
        - Field: path-pattern
          Values:
            - foo
      ListenerArn: !Ref 'Listener'
      Priority: 99

```
  * If present, please add links to the (official) documentation for clarification.

https://aws.amazon.com/blogs/aws/new-application-load-balancer-simplifies-deployment-with-weighted-target-groups/

  * Validate if the issue still exists with the latest version of `cfn-lint` and/or the latest Spec files

Exists in version 0.26.0 and after updating specfile with cfn-lint -u
