### ISSUE TITLE
Linting exception for valid HttpApi resource

### ISSUE THREAD

**Issue by sliedig** [aws-cloudformation/cfn-python-lint#1263]
*cfn-lint version: (`cfn-lint --version`)* 0.26.0

*Description of issue.*
HttpApi not recognised as a valid event source for type `AWS::Serverless::Function`

``` yaml
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: helloworld/
      Handler: app.lambda_handler
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
```

throws error

`E0001 Error transforming template: Resource with id [MyFunction] is invalid. Event with id [ApiEvent] is invalid. Resource dict has missing or invalid value for key Type. Event Type is: HttpApi.`

also referencing `${ServerlessHttpApi}` as in:

``` yaml
HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
```

throws error:

`E1019 Parameter ServerlessHttpApi for Fn::Sub not found at Outputs/HelloWorldApi/Value/Fn::Sub`

**Comment by kddejong** [comment]
I'll take a look.  E0001 usually comes from the sam translator package.  Do you know what version of that package you have installed?

**Comment by sliedig** [comment]
The latest release SAM V1.19.0

**Comment by kddejong** [comment]
I was able to replicate this error with `aws-sam-translator` `1.18.0`

E0001 Error transforming template: Resource with id [HelloWorldFunction] is invalid. Event with id [ApiEvent] is invalid. Resource dict has missing or invalid value for key Type. Event Type is: HttpApi.
test1.yaml:1:1

But it disappears when I upgrade to v1.19.0.  Any chance your installation is actually using `v1.18.0`

**Comment by PatMyron** [comment]
not seeing either of these after upgrading everything. Feel free to re-open if still experiencing after upgrading

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Runtime: provided
      CodeUri: helloworld/
      Handler: app.lambda_handler
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
```
