### ISSUE TITLE
UpdatePolicy on S3 Bucket

### ISSUE THREAD

**Issue by dscpinheiro** [aws-cloudformation/cfn-python-lint#1269]
cfn-lint version: 0.26.1 (installed with Homebrew)

*Description of issue*:
cfn-lint is asking for an [UpdatePolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html) on a S3 Bucket (which is not applicable). It also looks like it should be ignored: https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/rules/resources/UpdateReplacePolicyDeletionPolicyOnStatefulResourceTypes.py#L40

Sample template:
```yaml
Resources:
  Logs:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
```

Expected behavior: No output for `cfn-lint template.yaml`

Actual behavior:
```console
$ cfn-lint template.yaml 
W3011 Both UpdateReplacePolicy and DeletionPolicy are needed to protect resources from deletion
template.yaml:2:3
```
