### ISSUE TITLE
Rule W2506 is looking for a type of "ID" instead of String

### ISSUE THREAD

**Issue by rpatton4** [aws-cloudformation/cfn-python-lint#1280]
*cfn-lint version:* 0.26.2
*Description of Issue*
The rule W2506 in ImageId.py is checking that the value for an ImageId is of type AWS::EC2::Image::Id or WS::SSM::Parameter::Value<AWS::EC2::Image::Id>, but the CloudFormation documentation at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html indicates the value for ImageId is of type String. I have updated cfn-lint to the current version and run cfn-lint -u, this issue still appears.

The following template will generate the warning:

```
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  SampleAmiId:
    Description: >
      Provide an AMI ID
    Type: String

Resources:
  SampleServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref SampleAmiId
      KeyName: "SomeKey"
      InstanceType: "t2.medium"
```
The relevant section from the CloudFormation spec is: 

```
 "ImageId": {
          "Required": false,
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-computeenvironment-computeresources.html#cfn-batch-computeenvironment-computeresources-imageid",
          "PrimitiveType": "String",
          "UpdateType": "Immutable"
        },
```
