### ISSUE TITLE
E3008 Property "VpcId" can Fn::GetAtt when creating AWS::EC2::TransitGatewayAttachment

### ISSUE THREAD

**Issue by rgd11** [aws-cloudformation/cfn-python-lint#1287]
*cfn-lint version: (`cfn-lint --version`)* 
0.26.2

*Description of issue.*
- Trying to create a AWS::EC2::TransitGatewayAttachment in us-gov-west-1
- Assigning an SSM Parameter value to VpcId
```  
  rVpc:
    Type: AWS::EC2::VPC
    Properties:
      ...
  rSsmParameterVpcId:
    Type: AWS::SSM::Parameter
    Properties:
      ...
      Value: !Ref rVpc
  rTransitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      ...
      VpcId: !GetAtt rSsmParameterProdVdmsVpcId.Value
```
- Results in

> E3008 Property "VpcId" can Fn::GetAtt to a resource of types [AWS::EC2::SecurityGroup, AWS::EC2::Subnet] at Resources/.../Properties/VpcId/Fn::GetAtt

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
  * If present, please add links to the (official) documentation for clarification.
  * Validate if the issue still exists with the latest version of `cfn-lint` and/or the latest Spec files
* Feature request:
  * Please provide argumentation about the missing feature. Context is key!

Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)
