### ISSUE TITLE
Can't use conditional for DeletionPolicy/UpdateReplacePolicy

### ISSUE THREAD

**Issue by joelhess** [aws-cloudformation/cfn-python-lint#1308]
*cfn-lint version: 26.2

*Description of issue.*
Unable to use a conditional expression when specifying a value for `DeletionPolicy` or `UpdateReplacePolicy`. 

CFN Lint returns:
`[cfn-lint] E3035: DeletionPolicy values should be of string at Resources/ConfigInitFunctionLogGroup/DeletionPolicy`

Quotes or not around retain/delete doesn't matter.

YAML Snippet
```
ConfigInitFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: !If [IsProduction, "Retain", "Delete"] # Fails
    UpdateReplacePolicy: Retain # Works
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ConfigInitFunction}"
      RetentionInDays: !If [ IsProduction, 365,7]

```
