### ISSUE TITLE
More validation of SecurityGroupIngress

### ISSUE THREAD

**Issue by kgutwin** [aws-cloudformation/cfn-python-lint#1323]
*cfn-lint version: 0.27.0*

The following template passes cfn-lint:

```
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  BadSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: broken
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
```

However, the template fails to launch in CloudFormation, with the failure message "Invalid value 'Must specify both from and to ports with TCP/UDP.' for portRange."

At a minimum, it would be good to validate that both FromPort and ToPort are specified when IpProtocol is tcp or udp; however, there are probably other implicit security group requirements that could be caught by cfn-lint.
