### ISSUE TITLE
E0002 bug when using parameters for DynamoDB AttributeDefinitions

### ISSUE THREAD

**Issue by joshlartz** [aws-cloudformation/cfn-python-lint#1385]
*cfn-lint version: 0.28.2*

*Description of issue.*

Rule E3039 (added in 0.28.0) doesn't support Refs and results in a E0002 error for the template. 

Repeatable with this template snippet:

```
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
    HashKeyName:
        Description: Primary Key Name
        Type: String
        AllowedPattern: '[a-zA-Z0-9]*'
        MinLength: '1'
        MaxLength: '2048'
        ConstraintDescription: must contain only alphanumberic characters

    HashKeyType:
        Description: Primary Key Type
        Type: String
        Default: S
        AllowedPattern: '[S|N]'
        MinLength: '1'
        MaxLength: '1'
        ConstraintDescription: must be either S or N

    RangeKeyName:
        Description: Sort Key Name
        Type: String
        Default: 'NA'
        AllowedPattern: '[a-zA-Z0-9]*'
        MinLength: '0'
        MaxLength: '2048'
        ConstraintDescription: must contain only alphanumberic characters

    RangeKeyType:
        Description: Sort Key Type
        Type: String
        Default: S
        AllowedPattern: '[S|N]'
        MinLength: '0'
        MaxLength: '1'
        ConstraintDescription: must be either S or Ns

Conditions:
    isRangeKeyAvailable: !Not [ !Equals [ !Ref RangeKeyName, 'NA' ] ]

Resources:
    DynamoDBTable:
        DeletionPolicy: Delete
        UpdateReplacePolicy: Delete
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions: !If
                - isRangeKeyAvailable
                - - AttributeName: !Ref HashKeyName
                    AttributeType: !Ref HashKeyType
                  - AttributeName: !Ref RangeKeyName
                    AttributeType: !Ref RangeKeyType
                - - AttributeName: !Ref HashKeyName
                    AttributeType: !Ref HashKeyType
            KeySchema: !If
                - isRangeKeyAvailable
                - - AttributeName: !Ref HashKeyName
                    KeyType: HASH
                  - AttributeName: !Ref RangeKeyName
                    KeyType: RANGE
                - - AttributeName: !Ref HashKeyName
                    KeyType: HASH
```
