### ISSUE TITLE
Rule E3004 is not checking for DependsOn declarations

### ISSUE THREAD

**Issue by miparnisari** [aws-cloudformation/cfn-python-lint#1386]
*cfn-lint version*: 0.8.2

*Description of issue.*

The following template has a circular dependency:
```yaml
Resources:
  Resource:
    Type: AWS::SNS::Topic
    DependsOn: Resource2
  Resource2:
    Type: AWS::SNS::Topic
    DependsOn: Resource
```

but `cfn-lint` doesn't report any problems with it.
