### ISSUE TITLE
Different cases for E0000

### ISSUE THREAD

**Issue by Saichovsky** [aws-cloudformation/cfn-python-lint#1424]
*cfn-lint version: (0.28.4)*

Separate the error E0000 between null YAML values on one hand and jinja2 variables for keys on the other

I have a template that has Jinja2 variables, something of this sort:

```yaml
MyIAMRole:
  Type: AWS::IAM::Role
  Properties:
    Tags:
      - Name: {{jinja2value}}
      - Environment: 
      - Owner: aws.user
```
The `Name` tag has a jinja2 variable for the value and the `Environment` tag is blank, to simulate the case of a user who has forgotten to enter a value.
Running `aws cloudformation validate-template` on this template will give different errors for the two cases (the Jinja2 variable and the valueless key). However, with cfn-lint (even the latest version, both cases give the error E0000. I would like my linter to ignore the Jinja2 variables, but there is the risk of skipping missed values, which is an actual YAML syntax issue. aws cfn validate-template does not have error numbers that one can use to instruct the tool to ignore, but cfn-lint does. However, cfn-lint does not discriminate between these two kinds of errors.
