### ISSUE TITLE
AWS::AutoScaling::AutoScalingGroup MaxInstanceLifetime Validation

### ISSUE THREAD

**Issue by sideshowcecil** [aws-cloudformation/cfn-python-lint#1449]
*cfn-lint version: 0.29.2*

*Description of issue.*

When using the parameter `MaxInstanceLifetime` for `AWS::AutoScaling::AutoScalingGroup` we are hit with the following lint error:

```
$ cfn-lint templates/proj/rgs/rgs_autoscale_stretch_elb.yml
E3002 Invalid Property Resources/autoscalegroup/Properties/MaxInstanceLifetime
templates/proj/rgs/rgs_autoscale_stretch_elb.yml:194:7
```

The template which leads to the error:

```
[...]

  autoscalegroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: !Ref AvailabilityZones
      Cooldown: '300'
      HealthCheckGracePeriod: !Ref GracePeriod
      HealthCheckType: ELB
      MaxSize: !Ref MaxSize
      MinSize: !Ref MinSize
      MaxInstanceLifetime: !Ref MaxInstanceLifetime
      VPCZoneIdentifier: !Ref EC2SubnetIDs
      TargetGroupARNs:
        - !Ref elbtargetgroup
      LaunchConfigurationName: !Ref launchconfiguration
      Tags: [...]
        PropagateAtLaunch: true
      TerminationPolicies:
        - Default

[..]
```

It seems the parameter is currently not supported by cfn-lint, would be cool to see support for it.
