### ISSUE TITLE
Warning on condition keys that are not applicable to given actions

### ISSUE THREAD

**Issue by imrehg** [aws-cloudformation/cfn-python-lint#1489]
*cfn-lint version: (`cfn-lint 0.29.6`)*

*Description of issue.*

When writing IAM rules, not all actions accept all conditions. In case a non-acceptable condition is added to an action, it is just silently ignored, as much as I can tell. Thus can result in a while goose chase: "why my rule did not apply?"

For example, the S3 object-level rules in general do not accept `s3:prefix`-based conditions. Thus this template (arguably contrived, there could be better example) would result in a policy that is listed except the condition ignored (and thus applied at all cases):

```yaml
Resources:
  WarehouseBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "test-bucket"
  WarehouseBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WarehouseBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Principal: "*"
            Action: s3:GetObject
            Resource: !Join ["", [!GetAtt [WarehouseBucket, Arn], "/*"]]
            Condition:
              StringLike:
                s3:prefix: "hq/"
```

`cfn-lint` happily accepts it, though. It would be nice to at least warn, that the condition is not applicable.

For the applicable rules, I've checked  https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_actions-resources-contextkeys.html and https://iam.cloudonaut.io/
