### ISSUE TITLE
Any `templates` configuration in `.cfnlintrc` file is ignored

### ISSUE THREAD

**Issue by dnutels** [aws-cloudformation/cfn-python-lint#1509]
*cfn-lint version: 0.30.1*

**Issue**: Any `templates` configuration in `.cfnlintrc` file is ignored.

---
This is my `.cfnlintrc` file:

```
templates:
  - web-app/**/*.yml
include_checks:
  - I
```

I have the following folder structure:

```
├── web-app
│   ├── network
│   │   └── vpc.yml
│   └── root.yml
└── .cfnlintrc
```

`root.yml`:

```
Parameters:
  Environment:
    Type: String

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: network/vpc.yml
      Parameters:
        Environment: !Ref Environment
```

`web-app/network/vpc.yml`:

```

Parameters:
  Environment:
    Description: Deployment environment
    Type: String

Resources:
  ExperimentsVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsSupport: false
      EnableDnsHostnames: false
```
---

When executing `cfn-lint` with:

`cfn-lint web-app/root.yml -t web-app/**/*.yml `

the following **expected** errors are thrown:

```
W2001 Parameter Environment not used.
web-app/network/vpc.yml:6:3

I3011 The default action when replacing/removing a resource is to delete it. Set explicit values for UpdateReplacePolicy / DeletionPolicy on potentially stateful resource: Resources/VPC
web-app/root.yml:12:3
```

As you can see, one of the errors originates in `root.yml` file and the other in `web-app/network/vpc.yml`, meaning that `cfn-lint` correctly resolves template paths.

However, if I rely on `.cfnlintrc` file on providing the path glob to templates, and run `cfn-lint` with :

`cfn-lint web-app/root.yml `

the following error is thrown:

```
I3011 The default action when replacing/removing a resource is to delete it. Set explicit values for UpdateReplacePolicy / DeletionPolicy on potentially stateful resource: Resources/VPC
web-app/root.yml:12:3
```

which indicates that `web-app/network/vpc.yml` file hasn't been processed and that the `templates` configuration is ignored.

This puzzles me as the functionality seems fundamental and I've seen claims that it works, but haven't been able to find where I made a mistake.

**Comment by kddejong** [comment]
Since you are using `.cfnlintrc` to find the templates you just need to run `cfn-lint`.  By passing a file parameter you are overriding the `.cfnlintrc` configuration for that execution.  

If I run `cfn-lint` with your replicated setup I'm seeing both errors.

**Comment by dnutels** [comment]
@kddejong 

It does work.

I wonder how did I managed to not test that permutation amongst all those I did try and didn't succeed.

Thank you.

**Comment by PatMyron** [comment]
[documented in the README here](https://github.com/aws-cloudformation/cfn-python-lint/#precedence)

**Comment by kddejong** [comment]
I would add and will probably add to the docs if you use .cfnlintrc file you may wish to use the `pass_filenames` parameter to pre-commit.  Pre-commit by default will pass any changing files into cfn-lint running it individually.  By switching it to `false` we can fully just rely on `.cfnlintrc`

```
repos:
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.48.0 # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        name: AWS CloudFormation Linter
        pass_filenames: false
```
