### ISSUE TITLE
AWS::ElasticLoadBalancingV2::TargetGroup strict attributes

### ISSUE THREAD

**Issue by deleugpn** [aws-cloudformation/cfn-python-lint#1515]
*cfn-lint version: 0.30.1*

*Description of issue.*
The attributes `HttpCode` and `TargetGroupAttributes.Value` are too strict. HttpCode is [documented as String](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-targetgroup-matcher.html#cfn-elasticloadbalancingv2-targetgroup-matcher-httpcode), however it refers to Http Code, which are numeric values (e.g. 200, 302, etc).
Same logic applies to `TargetGroupAttributes.Value`. The value of `deregistration_delay.timeout_seconds` has to be specified in **seconds** and, therefore, must be a number.

```
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 120
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      HealthCheckPath: /nginx-health
      Matcher:
        HttpCode: 200
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30
        - Key: load_balancing.algorithm.type
          Value: least_outstanding_requests
      UnhealthyThresholdCount: 3
      TargetType: ip
      VpcId: !ImportValue VpcId
```
