### ISSUE TITLE
AWS::Logs::MetricFilter MetricValues permits invalid strings

### ISSUE THREAD

**Issue by trav-c** [aws-cloudformation/cfn-python-lint#1525]
`cfn-lint 0.30.1`

AWS::Logs::MetricFilter.Properties.MetricTransformations[*].MetricValue allows a bare string not starting with '$' which it appears is never actually valid, ie 
"MetricValue: length" vs "MetricValue: $length"

Assuming I'm reading the documentation correctly MetricValue must always either be a number OR start with a '$' character.

The following fragment lints, but is rejected by CloudFormation at runtime without a $ at the start of the named MetricValue field
```
    QueueLengthMetricFilter:
        Type: AWS::Logs::MetricFilter
        Properties:
            LogGroupName: !Ref LogGroup
            FilterPattern: '[date, time, tag="rh-sched*", x01=throttling, x02="jobs.", ..., x10=Len, x11=of, x12=job, x13="queue*",  length]'
            MetricTransformations:
              - MetricValue: length
                MetricNamespace: !Sub '${EnvironmentName}'
                MetricName: 'JobsQueued'
```

Note: I believe that this is also missed by the AWS ValidateTemplate API
