### ISSUE TITLE
Detect invalid regexes in AllowedPattern property of parameters

### ISSUE THREAD

**Issue by trav-c** [aws-cloudformation/cfn-python-lint#1565]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.32.1

*Description of issue.*
cfn-lint currently does not appear to validate that the contents of the AllowedPattern property of a template parameter contains a valid regular expression when present, it would be useful if cfn-lint could check this.

For example a template containing:
```
Parameters:
    MyTestParameter:
        Description: Test with invalid AllowedPattern
        Type: String
        AllowedPattern: '^abc|def)$'
        ConstraintDescription: Must match AllowedPattern
```

Is not currently flagged by cfn-lint, but is rejected at runtime by CloudFormation due to the invalid regular expression in the AllowedPattern property which is missing a '(' at the second character.
