### ISSUE TITLE
AWS::RDS::DBProxy and AWS::RDS::DBProxyTargetGroup resolves to wrong type

### ISSUE THREAD

**Issue by hoonoh** [aws-cloudformation/cfn-python-lint#1581]
*cfn-lint version: (`cfn-lint --version`)* : 0.33.0

*Description of issue.*
1. since `AWS::RDS::DBProxy` and `AWS::RDS::DBProxyTargetGroup` are not included in the latest release, did update with `cfn-lint -u`.
2. both `AWS::RDS::DBProxy` and `AWS::RDS::DBProxyTargetGroup` are being resolved as `AWS::ACMPCA::Certificate`

Both `AWS::RDS::DBProxy` and `AWS::RDS::DBProxyTargetGroup` are listed in CloudFormation Resource Specifications.

inspecting with [vscode extension](https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code)..
![image](https://user-images.githubusercontent.com/2078254/84346751-a5782480-abeb-11ea-9401-360ca190f6e9.png)

#### docs:
[AWS::RDS::DBProxy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbproxy.html#cfn-rds-dbproxy-enginefamily)
[AWS::RDS::DBProxyTargetGroup](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbproxytargetgroup.html)

#### rds-proxy.yml
```yml
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]

Resources:
  DBSecretRootRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - rds.amazonaws.com
      Policies:
        - PolicyName: 'DBSecretRootRolePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - Fn::ImportValue: !Sub DBSecretRootArn-${Stage}
  RDSPostgresDBProxy:
    Type: AWS::RDS::DBProxy
    Properties:
      DebugLogging: true
      DBProxyName: !Sub DBProxy-${Stage}
      EngineFamily: POSTGRESQL
      IdleClientTimeout: 120
      RequireTLS: true
      RoleArn: !GetAtt DBSecretRootRole.Arn
      Auth:
        - AuthScheme: SECRETS
          SecretArn:
            Fn::ImportValue: !Sub DBSecretUserArn-${Stage}
          IAMAuth: DISABLED
      VpcSubnetIds:
        - Fn::ImportValue: !Sub SubnetPublic1-${Stage}
        - Fn::ImportValue: !Sub SubnetPublic2-${Stage}
  RDSPostgresDBProxyTargetGroup:
    Type: AWS::RDS::DBProxyTargetGroup
    Properties:
      DBProxyName: !Ref RDSPostgresDBProxy
      DBInstanceIdentifiers:
        - Fn::ImportValue: !Sub DBName-${Stage}
      TargetGroupName: default
      ConnectionPoolConfigurationInfo:
        MaxConnectionsPercent: 12
        MaxIdleConnectionsPercent: 11
        ConnectionBorrowTimeout: 120

```

#### cfn-lint results:
```bash
$ cfn-lint templates/rds-proxy.yml 
E3002 Invalid Property Resources/RDSPostgresDBProxyTargetGroup/Properties/TargetGroupName
templates/rds-proxy.yml:54:7
```
