### ISSUE TITLE
AWS::Lambda::Function.FileSystemConfigs missing from the Resource Specification

### ISSUE THREAD

**Issue by xeres** [aws-cloudformation/cfn-python-lint#1598]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.33.1

*Description of issue.*
The latest cfn-lint still detects [FileSystemConfigs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-filesystemconfigs
) with AWS::Serverless::Function as an error.

**Comment by PatMyron** [comment]
Can you run `pip3 show aws-sam-translator | grep 'Version'` to make sure you have [`1.25.0`](https://github.com/awslabs/serverless-application-model/releases/tag/v1.25.0)+?

and see if it still occurs after `pip3 install aws-sam-translator --upgrade` if not?

and provide a sample template and error message if not?

**Comment by xeres** [comment]
I tried it, hmm...

```
$ pip3 show aws-sam-translator | grep 'Version'
Version: 1.25.0
$ pip3 install aws-sam-translator --upgrade
Requirement already up-to-date: aws-sam-translator in /home/xeres/.local/lib/python3.8/site-packages (1.25.0)
Requirement already satisfied, skipping upgrade: boto3~=1.5 in /home/xeres/.local/lib/python3.8/site-packages (from aws-sam-translator) (1.13.26)
Requirement already satisfied, skipping upgrade: six~=1.11 in /usr/lib/python3/dist-packages (from aws-sam-translator) (1.14.0)
Requirement already satisfied, skipping upgrade: jsonschema~=3.0 in /usr/lib/python3/dist-packages (from aws-sam-translator) (3.2.0)
Requirement already satisfied, skipping upgrade: botocore<1.17.0,>=1.16.26 in /home/xeres/.local/lib/python3.8/site-packages (from boto3~=1.5->aws-sam-translator) (1.16.26)
Requirement already satisfied, skipping upgrade: jmespath<1.0.0,>=0.7.1 in /home/xeres/.local/lib/python3.8/site-packages (from boto3~=1.5->aws-sam-translator) (0.9.5)
Requirement already satisfied, skipping upgrade: s3transfer<0.4.0,>=0.3.0 in /home/xeres/.local/lib/python3.8/site-packages (from boto3~=1.5->aws-sam-translator) (0.3.3)
Requirement already satisfied, skipping upgrade: urllib3<1.26,>=1.20; python_version != "3.4" in /usr/lib/python3/dist-packages (from botocore<1.17.0,>=1.16.26->boto3~=1.5->aws-sam-translator) (1.25.8)
Requirement already satisfied, skipping upgrade: python-dateutil<3.0.0,>=2.1 in /home/xeres/.local/lib/python3.8/site-packages (from botocore<1.17.0,>=1.16.26->boto3~=1.5->aws-sam-translator) (2.8.0)
Requirement already satisfied, skipping upgrade: docutils<0.16,>=0.10 in /home/xeres/.local/lib/python3.8/site-packages (from botocore<1.17.0,>=1.16.26->boto3~=1.5->aws-sam-translator) (0.15.2)
```

The minimum template for reproduce.
```
AWSTemplateFormatVersion: 2010-09-09
Description: SAM + Lambda + EFS
Transform: AWS::Serverless-2016-10-31

Parameters:
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

  VpcSubnetId:
    Type: AWS::EC2::Subnet::Id

Resources:
  EfsFileSystem:
    Type: AWS::EFS::FileSystem

  MountTarget:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EfsFileSystem
      SubnetId: !Ref VpcSubnetId
      SecurityGroups:
        - !Ref SecurityGroupId

  AccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref EfsFileSystem

  LambdaFunctionWithEfs:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        const fs = require('fs')
        const path = require('path')
        const efsMountPath = '/mnt/efs'
        exports.handler = async (event, context, callback) => {
          const directory = path.join(efsMountPath, event.body)
          const files = fs.readdirSync(directory)
          return files
        }
      Handler: index.handler
      MemorySize: 128
      Runtime: nodejs12.x
      Timeout: 3
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupId
        SubnetIds:
          - !Ref VpcSubnetId
      FileSystemConfigs:
        - Arn: !GetAtt AccessPoint.Arn
          LocalMountPath: /mnt/efs
```

Let me know if there is anything else I can do to help.
