### ISSUE TITLE
E2523 Only one of [VirtualName, Ebs, NoDevice] should be specified for Resources/LaunchTemplate/Properties/LaunchTemplateData/BlockDeviceMappings/0

### ISSUE THREAD

**Issue by ARMAAN7139** [aws-cloudformation/cfn-python-lint#1614]
cfn-lint 0.33.0

```
Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: DeviceName
          - Ebs:
              DeleteOnTermination: false
```

**Comment by PatMyron** [comment]
Reproduced, thanks for the template! Will need to look into this type and rule:

[`AWS::EC2::LaunchTemplate.BlockDeviceMapping`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping.html)

https://github.com/aws-cloudformation/cfn-python-lint/blob/fe0af928a4ab26a6cedfd76564a26c9a4120b14f/src/cfnlint/rules/resources/properties/OnlyOne.py#L13

If you need an immediate workaround, [individual rules can be ignored at the resource-level:](https://github.com/aws-cloudformation/cfn-python-lint#resource-based-metadata)
```yaml
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E2523
```
