### ISSUE TITLE
ElastiCache Replication Group: Invalid Property Resources/ReplicationGroup/Properties/MultiAZEnabled

### ISSUE THREAD

**Issue by zhangwenjia0326** [aws-cloudformation/cfn-python-lint#1629]
*cfn-lint version: (`cfn-lint 0.32.1`)*

*Properties MultiAZEnabled is considered invalid property for resource type AWS::ElastiCache::ReplicationGroup*

* Template linting issues: 
  * **We use taskcat container (image here: https://hub.docker.com/r/taskcat/taskcat, latest tag) to validate our CF templates.**
```
ReplicationGroup:
    Type: 'AWS::ElastiCache::ReplicationGroup'
    Properties:
      AutomaticFailoverEnabled: !Ref MultiAZSupport
      MultiAZEnabled: true
      CacheNodeType: !Ref CacheNodeType
      CacheSubnetGroupName: !Ref SubnetGroup
      Engine: redis
      NumCacheClusters: !Ref NumCacheClusters
      Port: !Ref RedisPort
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      ReplicationGroupDescription: !Ref ReplicationGroupDescription
      SecurityGroupIds:
        - !GetAtt 
          - SecurityGroup
          - GroupId
      SnapshotRetentionLimit: !Ref SnapshotRetentionLimit
      SnapshotWindow: !Ref SnapshotWindow
      AtRestEncryptionEnabled: false
      TransitEncryptionEnabled: false
```
  * [`AWS::ElastiCache::ReplicationGroup.MultiAZEnabled`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html#cfn-elasticache-replicationgroup-multiazenabled)
  * **We use the latest docker image of TaskCat, which do not use the latest cfn-lint. So we are stuck with 0.32.1.**
* Feature request:
  * **Please let us know if the latest version of cfn-lint fixes this, and we should reach out to TaskCat for them to update their cfn-lint version.**

Thank you for your time!
