### ISSUE TITLE
AutoPublishAlias property in Globals section throws E0001

### ISSUE THREAD

**Issue by LukaK** [aws-cloudformation/cfn-python-lint#1633]
*cfn-lint version: (`cfn-lint --version`)*
`cfn-lint 0.34.0`

*Description of issue.*
`AutoPublishAlias` in `Globals` section, referencing template parameter throws [`E0001`](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/docs/rules.md#E0001)
Having the same parameter in Function resource passes ok.

```
Transform: AWS::Serverless-2016-10-31
Parameters:
  Stage:
    Type: String
Globals:
  Function:
    Runtime: python3.8
    AutoPublishAlias: !Ref Stage
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      # AutoPublishAlias: !Ref Stage
      CodeUri: ..
      Handler: src.test.lambda_handler
```
`[cfn-lint] E0001: Error transforming template: Resource with id [TestFunction] is invalid. 'AutoPublishAlias' must be a string or a Ref to a template parameter`
