### ISSUE TITLE
Wrong validation for Lifecycle property under AWS::Backup::BackupPlan resource

### ISSUE THREAD

**Issue by shiva-chaganti** [aws-cloudformation/cfn-python-lint#1678]
*cfn-lint version*: 0.29.0

**Description of issue.**

Getting validation error [_E3002 Property is an object instead of List_], for [`AWS::Backup::BackupPlan.Lifecycle`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-backup-backupplan-backupruleresourcetype.html#cfn-backup-backupplan-backupruleresourcetype-lifecycle)

**Sample to produce error**

```
  rBackupPlanStandard:
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: generic-backup-plan
        BackupPlanRule:
          -
            RuleName: generic-daily-backups
            TargetBackupVault: !Ref rBackupVaultDaily
            ScheduleExpression: "cron(0 5 ? * * *)"
            Lifecycle:
              DeleteAfterDays: 7
```
