### ISSUE TITLE
resources and parameters must have unique names

### ISSUE THREAD

**Issue by PatMyron** [aws-cloudformation/cfn-python-lint#1689]
```yaml
Parameters:
  Name:
    Type: String
Resources:
  Name:
    Type: AWS::SNS::Topic
```
```bash
Template error: all resources and parameters must have unique names. Common name(s):[Name]
```
