### ISSUE TITLE
Exceptions in E3002 and E3003 when evaluating AWS::StepFunctions::StateMachine.TagsEntry for eu-west-2

### ISSUE THREAD

**Issue by JamieEdge** [aws-cloudformation/cfn-python-lint#1695]
Given the following template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
  
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        StartAt: Example
      Role: !GetAtt StateMachineRole.Arn
```

The following linting errors are output when using cfn-lint 0.35.1 with the eu-west-2 region specified:

```
E0002 Unknown exception while processing rule E3002: 'AWS::StepFunctions::StateMachine.TagsEntry'
example.yml:1:1

E0002 Unknown exception while processing rule E3003: 'AWS::StepFunctions::StateMachine.TagsEntry'
example.yml:1:1
```

The errors are not shown when specifying the region as eu-west-1 or us-east-1.
