### ISSUE TITLE
Using If Condition for AWS::S3::Bucket ReplicationConfiguration property

### ISSUE THREAD

**Issue by joeyancheta** [aws-cloudformation/cfn-python-lint#1713]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.34.0
```
E3002 Expecting an object at Resources/CloudAvailS3Bucket/Properties/ReplicationConfiguration/Fn::If/1
devops/infra/cloudavail.yaml:146:11

E3002 Expecting an object at Resources/CloudAvailS3Bucket/Properties/ReplicationConfiguration/Fn::If/2
```

```
    CloudAvailS3Bucket:
    Type: AWS::S3::Bucket
      ReplicationConfiguration: !If
        - S3ReplicationEnabled
        - - 
             Role: !GetAtt CloudAvailReplicationRole.Arn
             Rules: 
               - Destination: 
                      Bucket: arn:aws:s3:::cloudavail.replication.bucket
              Status: Enabled
        - - 
             !Ref "AWS::NoValue"
```
