### ISSUE TITLE
E2529 error with multiple `AWS::Logs::SubscriptionFilter` resources.

### ISSUE THREAD

**Issue by jeffersonjack** [aws-cloudformation/cfn-python-lint#1743]
*cfn-lint version: 0.38.0*

*[`E2529`](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/docs/rules.md#E2529) error with multiple [`AWS::Logs::SubscriptionFilter`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-subscriptionfilter.html) resources.*

I have a CloudFormation template (using AWS SAM) that has multiple SubscriptionFilters. These SubscriptionFilters have the same `LogGroupName`, which causes an `E2529` error despite these filters having separate FilterPatterns. The template passes the [`aws cloudformation validate-template`](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/validate-template.html) command.

[`src/cfnlint/rules/resources/lmbd/EventsLogGroupName.py`](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/rules/resources/lmbd/EventsLogGroupName.py)

```
  MainFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 14
      LogGroupName: !Join ["", [/aws/lambda/, !Ref MainFunction]]

  MainFunctionLogFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Ref LogIngestionARN
      FilterPattern: "FilterPattern1"
      LogGroupName: !Ref MainFunctionLogGroup

  SecondaryLogFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !Ref LogIngestionARN
      FilterPattern: "FilterPattern2"
      LogGroupName: !Ref MainFunctionLogGroup
```
