### ISSUE TITLE
New Rule for AWS::ECS::CapacityProvider resource

### ISSUE THREAD

**Issue by raknass** [aws-cloudformation/cfn-python-lint#1745]
*cfn-lint version: 0.24.3

*Description of issue.*
Fails to validate AWS:ECS:CapacityProvider resource. Cloudformation support added recently.
```
E3002 Invalid Property Resources/Cluster/Properties/CapacityProviders
E3001 Invalid or unsupported Type AWS::ECS::CapacityProvider for resource CapacityProvider
```

```
CapacityProvider:
    Type: AWS::ECS::CapacityProvider
    Properties:
      AutoScalingGroupProvider:
        AutoScalingGroupArn: !Ref AutoScalingGroup
        ManagedScaling:
          Status: ENABLED
          TargetCapacity: 100
          MinimumScalingStepSize: 1
          MaximumScalingStepSize: 100
        ManagedTerminationProtection: DISABLED
```
