### ISSUE TITLE
KmsKeyId not valid property for AWS::Logs::LogGroup

### ISSUE THREAD

**Issue by vennemp** [aws-cloudformation/cfn-python-lint#1763]
*cfn-lint version: (`cfn-lint --version`)*
0.39.0
*Description of issue.*
```yaml  
  CloudWatchKMS:
    Type: AWS::KMS::Key
    Properties:
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
          - Sid: Allow Cloudwatch Access
            Effect: Allow
            Principal:
              Service: logs.region.amazonaws.com
            Action:
              - kms:Encrypt*
              - kms:Decrypt*
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:Describe*
            Resource: '*'
  MessagesLogCWGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      KmsKeyId: !GetAtt CloudWatchKMS.Arn
      LogGroupName: messages
      RetentionInDays: 30
```

E3002 Invalid Property Resources/MessagesLogCWGroup/Properties/KmsKeyId
template.yaml:627:7
