### ISSUE TITLE
AWS::ApiGateway::Authorizer - E3008 Property "RestApiId" has no valid Fn::GetAtt options

### ISSUE THREAD

**Issue by JamieEdge** [aws-cloudformation/cfn-python-lint#1806]
Given the following template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  ProvisionedProduct:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: example
      ProvisioningArtifactName: v1

  Authoriser:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      RestApiId: !GetAtt ProvisionedProduct.Outputs.RestApiId
      Type: TOKEN
```

The following error is output when using cfn-lint 0.42.0:

```
E3008 Property "RestApiId" has no valid Fn::GetAtt options at Resources/Authoriser/Properties/RestApiId/Fn::GetAtt
template.yml:13:7
```
