### ISSUE TITLE
E3021 after upgrading to cfn_lint-0.44.0

### ISSUE THREAD

**Issue by AlessandroLorenzi** [aws-cloudformation/cfn-python-lint#1833]
cfn-lint version: cfn_lint-0.44.0

Hi! 

After upgrading to version cfn_lint 0.44.0 don't validate  AWS::Events::Rule

This was reported valid since yesterday:

```yaml
  TaskSchedule:
    Type: AWS::Events::Rule
    Properties:
      Description: xxxxxxxxx
      Name: !Join ["-", [!Ref EnvironmentName, scheduled, !Ref App]]
      ScheduleExpression: "cron(15 9 * * ? *)"
      State: "ENABLED"
      Targets:
        - Arn:
            Fn::ImportValue: !Sub ${EnvironmentName}-microservice-cluster-arn
          RoleArn: !GetAtt ServiceRole.Arn
          Id: my-task
          EcsParameters:
            TaskCount: 1
            TaskDefinitionArn: !Ref TaskDefinition
```

The error reported is: `E3021 An Events Rule can have up to 5 Targets`

There is one Target so should still be valid
