### ISSUE TITLE
Exception processing E3037 for AWS::S3::Bucket.Transition.TransitionDate

### ISSUE THREAD

**Issue by asjohnston-asf** [aws-cloudformation/cfn-python-lint#1881]
```
$ cfn-lint --version
cfn-lint 0.44.5
```

The `TransitionDate` property is defined with `PrimitiveType: "Timestamp"`:

```yaml
AWSTemplateFormatVersion: 2010-09-09

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            Transitions:
              - StorageClass: INTELLIGENT_TIERING
                TransitionDate: 2021-01-01T00:00:00.000Z
```

This is a valid template and can be successfully deployed, but `cfn-lint` fails with:

```
$ cfn-lint scratch.yml
E0002 Unknown exception while processing rule E3037: Object of type datetime is not JSON serializable
scratch.yml:1:1
```

Running with `--debug` shows the exception is generated at https://github.com/aws-cloudformation/cfn-python-lint/blob/c7658511bd7066417682103f21f71983c67ea6d0/src/cfnlint/rules/resources/properties/ListDuplicates.py#L36

Quoting the TransitionDate value suppresses this error, e.g. `TransitionDate: "2021-01-01T00:00:00.000Z"`
