### ISSUE TITLE
E1012: Ref <layer> not found as a resource or parameter when using SAM Globals

### ISSUE THREAD

**Issue by alanwill** [aws-cloudformation/cfn-python-lint#1896]
*cfn-lint version: 0.44.6*

*Description of issue.*
When using [Globals](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html) as part of a SAM template and declaring a global layer, I'm getting the following error: `[cfn-lint] E1012: Ref layerAwscore not found as a resource or parameter`

Please provide as much information as possible:

Using the template below will generate the error, `[cfn-lint] E1012: Ref layerAwscore not found as a resource or parameter`

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Globals:
  Function:
    Runtime: python3.8
    Handler: app.handler
    MemorySize: 128
    Timeout: 30
    AutoPublishAlias: live
    Tracing: Active
    Layers:
      - !Ref layerAwscore

Resources:
  layerAwscore:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${stackName}-awscore-${stage}
      Description: Core AWS packages, boto3 + aws-xray-sdk
      ContentUri: ../layers/awscore
      CompatibleRuntimes:
        - python3.8
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.8

```

**Comment by kddejong** [comment]
For tracking the transformed template is 
```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "layerAwscore7125176640": {
      "DeletionPolicy": "Delete",
      "Properties": {
        "CompatibleRuntimes": [
          "python3.8"
        ],
        "Content": {
          "S3Bucket": "bucket",
          "S3Key": "value"
        },
        "Description": "Core AWS packages, boto3 + aws-xray-sdk",
        "LayerName": {
          "Fn::Sub": "${stackName}-awscore-${stage}"
        }
      },
      "Type": "AWS::Lambda::LayerVersion"
    }
  }
}
```

**Comment by kddejong** [comment]
@alanwill little oddness here.  When SAM translates the serverless functions it changes the names. If you used the template below the error goes away as the translated name gets put in appropriately.
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Globals:
  Function:
    Runtime: python3.8
    Handler: app.handler
    MemorySize: 128
    Timeout: 30
    AutoPublishAlias: live
    Tracing: Active
    Layers:
      - !Ref layerAwscore

Resources:
  function:
    Type: AWS::Serverless::Function
    Properties: {}
  layerAwscore:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${stackName}-awscore-${stage}
      Description: Core AWS packages, boto3 + aws-xray-sdk
      ContentUri: ../layers/awscore
      CompatibleRuntimes:
        - python3.8
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.8

```

translates to 
```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "function": {
      "Properties": {
        "Code": {
          "S3Bucket": "bucket",
          "S3Key": "value"
        },
        "Handler": "app.handler",
        "Layers": [
          {
            "Ref": "layerAwscore7125176640"
          }
        ],
        "MemorySize": 128,
        "Role": {
          "Fn::GetAtt": [
            "functionRole",
            "Arn"
          ]
        },
        "Runtime": "python3.8",
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ],
        "Timeout": 30,
        "TracingConfig": {
          "Mode": "Active"
        }
      },
      "Type": "AWS::Lambda::Function"
    },
    "functionAliaslive": {
      "Properties": {
        "FunctionName": {
          "Ref": "function"
        },
        "FunctionVersion": {
          "Fn::GetAtt": [
            "functionVersion55ff35af87",
            "Version"
          ]
        },
        "Name": "live"
      },
      "Type": "AWS::Lambda::Alias"
    },
    "functionRole": {
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
          "arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess"
        ],
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ]
      },
      "Type": "AWS::IAM::Role"
    },
    "functionVersion55ff35af87": {
      "DeletionPolicy": "Retain",
      "Properties": {
        "FunctionName": {
          "Ref": "function"
        }
      },
      "Type": "AWS::Lambda::Version"
    },
    "layerAwscore7125176640": {
      "DeletionPolicy": "Delete",
      "Properties": {
        "CompatibleRuntimes": [
          "python3.8"
        ],
        "Content": {
          "S3Bucket": "bucket",
          "S3Key": "value"
        },
        "Description": "Core AWS packages, boto3 + aws-xray-sdk",
        "LayerName": {
          "Fn::Sub": "${stackName}-awscore-${stage}"
        }
      },
      "Type": "AWS::Lambda::LayerVersion"
    }
  }
}
```
