### ISSUE TITLE
 AWS::Serverless::HttpApi and AWS::Serverless::Api both have a Description property

### ISSUE THREAD

**Issue by kstro21** [aws-cloudformation/cfn-python-lint#1908]
*cfn-lint version: (` 0.45.0`)*

Resource of type [AWS::Serverless::HttpApi](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html) and [AWS::Serverless::Api](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html) both have a `Description` property in the docs but if I add it to a template then `cfn-lint` fails with 
>[cfn-lint] E0001: Error transforming template: Resource with id [MyApi] is invalid. property Description not defined for resource of type AWS::Serverless::HttpApi

Here is an example

```YAML
MyApi:
    Type: 'AWS::Serverless::HttpApi'
    Properties:
      Description: 'Client API'
      StageName: !Ref 'StageName'
      CorsConfiguration:
        AllowCredentials: true
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigins: '*'
```

The template deploys ok using `sam deploy` so it is not an error. I'm already using the latest version of `cfn-lint` and already did `cfn-lint -u`

Hope this gets fixed soon.

PS: nice job!
