### ISSUE TITLE
AWS::ElasticLoadBalancingV2::TargetGroup.ProtocolVersion - E3002

### ISSUE THREAD

**Issue by JamieEdge** [aws-cloudformation/cfn-python-lint#1921]
Given the following template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Protocol: HTTPS
      ProtocolVersion: HTTP2
```

The following error is output when using cfn-lint 0.45.0:

```
E3002 Invalid Property Resources/TargetGroup/Properties/ProtocolVersion
template.yml:8:7
```
