### ISSUE TITLE
AWS::ServiceCatalog::CloudFormationProvisionedProduct.Outputs

### ISSUE THREAD

**Issue by purvish14** [aws-cloudformation/cfn-python-lint#1931]
cfn-lint version: 0.47.0

Given the following example template:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Serverless Stack
Resources:
    SimpleLambda:
      Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
      Properties:
        ProductName: Basic Lambda
        ProvisioningArtifactName: '1.0'
      
    SimpleApiGateway:
      Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
      Properties:
        ProductName: API Gateway
        ProvisioningArtifactName: '1.0'
        ProvisioningParameters:
            -
              Key: LambdaArn
              Value: !GetAtt [SimpleLambda, Outputs.SCLambdaArn]
```

The following linting errors are thrown:
```
E1010 Invalid GetAtt SimpleLambda.Outputs.SCLambdaArn for resource SimpleApiGateway
product.template.yaml:18:15
```

This issue was fixed in #1659 PR, but I'm still getting this error.

Documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicecatalog-cloudformationprovisionedproduct.html#aws-resource-servicecatalog-cloudformationprovisionedproduct--examples
