### ISSUE TITLE
E3001 Invalid or unsupported Type AWSQS::Kubernetes::Helm for resource

### ISSUE THREAD

**Issue by RishabhGuptaIn** [aws-cloudformation/cfn-python-lint#1932]
*cfn-lint version: (`cfn-lint --version`)*

*Description of issue.*
 AWSQS::Kubernetes::Helm & AWSQS::Kubernetes::Resource are not recognized by cfn-lint

I'm trying to deploy one cfn template from AWS Quick Start EKS repo

code snippet :

```yaml
LoadBalancerControllerServiceAccount:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref EksClusterName
      Namespace: kube-system
      Manifest: !Sub |
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          labels:
            app.kubernetes.io/name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: ${LoadBalancerControllerIAMRole.Arn}
          name: aws-load-balancer-controller
  LoadBalancerControllerHelmChart:
    Type: "AWSQS::Kubernetes::Helm"
    DependsOn: LoadBalancerControllerServiceAccount
    Metadata: { cfn-lint: { config: { ignore_checks: [E3012] } } }
    Properties:
      ClusterID: !Ref EksClusterName
      Namespace: kube-system
      Repository: https://aws.github.io/eks-charts
      Chart: aws-load-balancer-controller
      Values:
        clusterName: !Ref EksClusterName
        serviceAccount.create: false
        serviceAccount.name: aws-load-balancer-controller
        region: !Sub "${AWS::Region}"
        image.repository: !FindInMap [RegionMap, !Ref "AWS::Region", lbrepo]
      ValueYaml: |
        nodeSelector:
          kubernetes.io/os: linux
```

          
Url : https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/templates/amazon-eks-load-balancer-controller.template.yaml#L221-L252
and while using the cfn-lint with the template, I'm getting the unsupported type error.
