### ISSUE TITLE
Support linting Elastic Beanstalk .config files

### ISSUE THREAD

**Issue by alexjurkiewicz** [aws-cloudformation/cfn-python-lint#524]
[Elastic Beanstalk application versions can contain customisation of the base EB stack using .config files.](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environment-resources.html)

For example, here's an example file which adds a target tracking scaling policy to the environment's auto scaling group:

```yaml
Resources:
  ScalingPolicyRequests:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName:
        Ref: AWSEBAutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ALBRequestCountPerTarget
          ResourceLabel:
            Fn::Sub: ${AWSEBV2LoadBalancer.LoadBalancerFullName}/${AWSEBV2LoadBalancerTargetGroup.TargetGroupFullName}
        TargetValue: 1500
```

When an application version with this file in it is deployed, Elastic Beanstalk merges this resource snippet with the base template file and updates the stack.

There are a few issues with linting these files right now:

1. There can be references to resources in the base template which cfn-lint can't find. All base template resources start with `AWSEB`
2. There can be top-level keys which aren't part of the template definition: `option_settings`, `packages`, `groups`, `users`, `sources`, `files`, `commands`, `services`, `container_commands`

I'd like to propose that cfn-lint add support for linting this file type. It would do this by only checking the Resources key, and ignoring references too resources starting with `AWSEB`.

Support could be automatic detection based on file name (`*.config`, which is required by EB) or adding a new parameter `--file-type cfn|eb` (defaulting to cfn of course).

If you'd be happy to accept these changes, I'm happy to have a crack in the new year :)

**Comment by PatMyron** [comment]
> There can be references to resources in the base template which cfn-lint can't find



**Can workaround with [resource-level ignores](https://github.com/aws-cloudformation/cfn-python-lint#resource-based-metadata):**

```yaml
  ScalingPolicyRequests:
    Type: AWS::AutoScaling::ScalingPolicy
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E1010 # GetAtt
          - E1012 # Ref
          - E1019 # Sub
          - E3005 # DependsOn
```

> There can be top-level keys which aren't part of the template definition

**ignoring [`E1001`](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/docs/rules.md#E1001) should mitigate this:**
https://github.com/aws-cloudformation/cfn-python-lint/blob/b6080aa3bd1b7fbe153125c49925beb5186dfab0/src/cfnlint/rules/templates/Base.py#L28

---

I think we're unlikely to formally pick this up ourselves, but hopefully that helps point in the direction of rules that'd be affected
