### ISSUE TITLE
Spec Bug "AWS::CloudWatch::Alarm" "MetricName" (required) ?

### ISSUE THREAD

**Issue by fatbasstard** [aws-cloudformation/cfn-python-lint#622]
According to the Documentation and the Spec files the `AWS::CloudWatch::Alarm` `MetricName` is not required:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html#cfn-cloudwatch-alarms-metricname

But deploying an Allarm without MetricName results in an error:
![image](https://user-images.githubusercontent.com/35613489/51988122-355c7900-24a4-11e9-8137-d95246ec4f41.png)

Used resource:
```
  CloudWatchAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      EvaluationPeriods: 1
      Statistic: "SampleCount"
      Threshold: 0.0
      TreatMissingData: "notBreaching"
      Unit: "Terabits/Second"
```
