### ISSUE TITLE
wrong cors error with AWS::Serverless::API

### ISSUE THREAD

**Issue by gojko** [aws-cloudformation/cfn-python-lint#698]
*cfn-lint version*: 0.15.0

*Description of issue*: CFN Lint complains about a perfectly valid SAM stack (deploys successfully using CloudFormation), when Cors configuration is turned on. 

The error is: `E0001 Resource with id [WebApi] is invalid. Cors works only with inline Swagger specified in 'DefinitionBody' property`

a minimal template displaying the error:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  AppStage:
    Type: String
Resources:
  WebAssetsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        ErrorDocument: 404.html
        IndexDocument: index.html
  WebApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref AppStage
      Cors: !Sub "'${WebAssetsS3Bucket.WebsiteURL}'"
```
