### ISSUE TITLE
APIGW Authoriser definition not supported

### ISSUE THREAD

**Issue by xiaket** [aws-cloudformation/cfn-python-lint#724]
*cfn-lint version: cfn-lint 0.16.0*

Hi, there!

Thanks for this great tool! It looks really promising!  :)

I think this is yet another SAM issue. The following piece of template works in Cloudformation, but  cfn-lint think otherwise :P

```
  API:                                                                                                                                                                  
    Type: "AWS::Serverless::Api"                                                                                                                                        
    Properties:                                                                                                                                                         
      StageName: Prod                                                                                                                                                   
      Auth:                                                                                                                                                             
        DefaultAuthorizer: LambdaRequestAuth                                                                                                                            
        Authorizers:                                                                                                                                                    
          LambdaRequestAuth:                                                                                                                                            
            FunctionPayloadType: REQUEST                                                                                                                                
            FunctionArn: !Ref AuthoriserArnParameter                                                                                                                    
            Identity:                                                                                                                                                   
              Headers:                                                                                                                                                  
                - authorization                                                                                                                                         
              ValidationExpression: "Bearer\ .*"                                                                                                                        
              ReauthorizeEvery: 0
```

The error message is:

```
2019-03-14 15:18:18,767 - cfnlint - DEBUG - Setting AWS_DEFAULT_REGION to us-east-1
2019-03-14 15:18:18,854 - cfnlint - DEBUG - Completed linting of file: ../../server/template.yaml
E0001 Error transforming template: Resource with id [API] is invalid. Auth works only with inline Swagger specified in 'DefinitionBody' property
../../server/template.yaml:1:1
```
