### ISSUE TITLE
Trust Policy check counts Functions in length (E2508 Role trust policy JSON text cannot be longer than 2048 characters)

### ISSUE THREAD

**Issue by ikben** [aws-cloudformation/cfn-python-lint#738]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.16.0

*Description of issue.*
When using functions in a Trust Policy, they get counted as characters and trigger the length check. This may cause false positives eg, if there is an "If" function in there, or false negatives, eg if the there is a Ref('short') that returns a long value.
 
Example template:
```
Parameters:
  # Testing with this set to No will deploy
  LimitAdminUse:
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'No'
    Type: String
  UserName:
    Type: String
Conditions:
  IsLimitAdminUse: !Equals
    - !Ref 'LimitAdminUse'
    - 'Yes'
Resources:
  AdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: 'true'
            Effect: Allow
            Principal:
              AWS: !If
                - IsLimitAdminUse
                # We repeat a lot, to get more characters, this could be all different usernames in a real template
                - - !Sub
                    - arn:aws:iam::${Account}:user/${User}
                    - Account: !Ref AWS::AccountId
                      User: !Ref UserName
                  - !Sub
                    - arn:aws:iam::${Account}:user/${User}
                    - Account: !Ref AWS::AccountId
                      User: !Ref UserName
                  - !Sub
                    - arn:aws:iam::${Account}:user/${User}
                    - Account: !Ref AWS::AccountId
                      User: !Ref UserName
                  - !Sub
                    - arn:aws:iam::${Account}:user/${User}
                    - Account: !Ref AWS::AccountId
                      User: !Ref UserName
                  - !Sub
                    - arn:aws:iam::${Account}:user/${User}
                    - Account: !Ref AWS::AccountId
                      User: !Ref UserName
                  - !Sub
                    - arn:aws:iam::${Account}:user/${User}
                    - Account: !Ref AWS::AccountId
                      User: !Ref UserName
                  - !Sub
                    - arn:aws:iam::${Account}:user/${User}
                    - Account: !Ref AWS::AccountId
                      User: !Ref UserName
                  - !Sub
                    - arn:aws:iam::${Account}:user/${User}
                    - Account: !Ref AWS::AccountId
                      User: !Ref UserName
                  - !Sub
                    - arn:aws:iam::${Account}:user/${User}
                    - Account: !Ref AWS::AccountId
                      User: !Ref UserName
                  - !Sub
                    - arn:aws:iam::${Account}:user/${User}
                    - Account: !Ref AWS::AccountId
                      User: !Ref UserName
                  - !Sub
                    - arn:aws:iam::${Account}:user/${User}
                    - Account: !Ref AWS::AccountId
                      User: !Ref UserName
                  - !Sub
                    - arn:aws:iam::${Account}:user/${User}
                    - Account: !Ref AWS::AccountId
                      User: !Ref UserName
                  - !Sub
                    - arn:aws:iam::${Account}:user/${User}
                    - Account: !Ref AWS::AccountId
                      User: !Ref UserName
                  - !Sub
                    - arn:aws:iam::${Account}:user/${User}
                    - Account: !Ref AWS::AccountId
                      User: !Ref UserName
                  - !Sub
                    - arn:aws:iam::${Account}:user/${User}
                    - Account: !Ref AWS::AccountId
                      User: !Ref UserName
                - !Sub
                  - arn:aws:iam::${Account}:root
                  - Account: !Ref AWS::AccountId
            Sid: ''
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Path: /
```

* Feature request:
Getting this check to work reliably is hard, there are some mays to make it better.

1. Ignore the check if there are functions in the trust policy
2. (a bit better) Count every function as 0 characters (this should return the minimum number of characters)
2. (even better). Count every function that returns a value as 0, and handle If's as the maximum of its branches.
