### ISSUE TITLE
Improve s3 bucket policy linting

### ISSUE THREAD

**Issue by chizou** [aws-cloudformation/cfn-python-lint#753]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.16.0

*Description of issue.*
Add better linting for s3 bucket policies

I have the following template:
```
  ReportBucketPolicy:
    Properties:
      Bucket: !Ref 'ReportBucket'
      PolicyDocument:
        Statement:
          - Action:
              - s3:ListBucket
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Ref 'OrgId'
            Effect: Allow
            Principal: '*'
            Resource:
              - !Sub '${ReportBucket.Arn}/*'
            Sid: AllowOrgAccess
        Version: '2012-10-17'
    Type: AWS::S3::BucketPolicy
```
I initially had a typo so that I forgot the `$` in the `Sub()` so that it was like this: `- !Sub '${ReportBucket.Arn}/*'`

Can cfn-lint be made to catch that the resource specified was invalid?

The above template also has an issue because the resource shouldn't have a `*` for `s3:ListBucket`. This is the error that CloudFormation returns: `Action does not apply to any resource(s) in statement`

Is it within cfn-lint's scope to validate PolicyDocuments?
