### ISSUE TITLE
E0002 Unknown exception while processing rule E3012: 'int' object has no attribute 'start_mark'

### ISSUE THREAD

**Issue by forkinme** [aws-cloudformation/cfn-python-lint#768]
**cfn-lint version:**
0.17.0

**Exception:**
E0002 Unknown exception while processing rule E3012: 'int' object has no attribute 'start_mark'
template.yml:1:1

**Example template:**
```yaml
AWSTemplateFormatVersion: 2010-09-09
Resources:
  emrStep:
    Type: 'AWS::EMR::Step'
    Properties:
      ActionOnFailure: CANCEL_AND_WAIT
      HadoopJarStep:
        Args:
          - string
          - 2
          - otherstring
        Jar: command-runner.jar
      JobFlowId: 'foo'
      Name: 'bar'
```

**Explanation:**
All items in the list for Resources.emrStep.Properties.HadoopJarStep.Args should be of type string per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emr-step-hadoopjarstepconfig.html, when a non-string value is provided cfn-lint generates an exception instead of noting the error.

Changing the args to the correct format by removing the `2` or putting quotes around it resolves the exception.

The (actual) template deploys successfully even though it has some ints instead of a strings in the args like the example does
