### ISSUE TITLE
AWS::Serverless::Application S3 Location support

### ISSUE THREAD

**Issue by eaddingtonwhite** [aws-cloudformation/cfn-python-lint#772]
*cfn-lint version: 0.16.0

*Description of issue.*

If I specify a s3 url in location section of resource`AWS::Serverless::Application`  the cfn lint fails with the following error.

**Resource**
```
  TestNest:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.amazonaws.com/testbucket32315/test-nest.yaml
```
**Error**
```
E0001 Error transforming template: Resource with id [TestNest] is invalid. Resource is missing the required [ApplicationId] property.
template.yaml:1:1
```

Per docs here this should be ok.
https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#example-awsserverlessapplication
