### ISSUE TITLE
E3025 RDS Instance Type db.t3 Support

### ISSUE THREAD

**Issue by benmontour-wf** [aws-cloudformation/cfn-python-lint#806]
*cfn-lint version: (`0.18.1 w/ latest Spec files`)*

*Description of issue:*
When attempting to specify an RDS Instance Type of the new db.t3 instances cfn-lint throws a E3025 error stating that a db.t3 is incompatible with engine type mysql in region us-east-1.
Looking at [RdsProperties.json](../blob/master/src/cfnlint/data/AdditionalSpecs/RdsProperties.json) it appears that the new db.t3 instance types have not been added yet.
Looking at the reference page [Amazon RDS for MySQL Pricing](https://aws.amazon.com/rds/mysql/pricing/) the db.t3 instances are supported when using mysql as the engine type.

*Example Code:*
```yaml
AppDB
  Type: AWS::RDS::DBInstance
  Properties:
    DBInstanceClass: db.t3.large
    Engine: mysql
```
