### ISSUE TITLE
Add support to use intrinsic functions, when dynamically referencing an SSM Parameter within CloudFormation template.

### ISSUE THREAD

**Issue by razhamma** [aws-cloudformation/cfn-python-lint#836]
**Issue Description**
Customers face template invalidation errors upon trying to substitute/reference a value for "parameter-name/version" inside:
```
{{resolve:ssm:parameter-name:version}}
{{resolve:ssm-secure:parameter-name:version}}  
```

**Findings**
helpers.py has a regex as follow:
```
REGEX_DYN_REF_SSM = re.compile(r'^.*{{resolve:ssm:[a-zA-Z0-9_\.\-/]+:\d+}}.*$')
REGEX_DYN_REF_SSM_SECURE = re.compile(r'^.*{{resolve:ssm-secure:[a-zA-Z0-9_\.\$\-/]+:\d+}}.*$')
```
- This regex: `[a-zA-Z0-9_\.\-/]+:\d+` is restricting customers to use intrinsic functions when using dynamic referencing for SSM Parameter under some resource specifications. 
- Changing this regex to something like `[a-zA-Z0-9_\.\{\}\:\"\!\-/]+:\d+` might help.

Below is the sample template that can be used for reproducing the issue for any already existing SSM parameter:
```
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ParameterName:
    Type: String
    Description: testing value for SSM parameter-value
  ParameterVersion:
    Type: Number
    Description: testing value for SSM version
Resources:
  S3bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join 
        - ''
        - - '{'
          - '{'
          - 'resolve:'
          - 'ssm:'
          - !Ref ParameterName
          - ':'
          - !Ref ParameterVersion
          - '}'
          - '}'
          - '-test-bucket'
```

**Comment by kddejong** [comment]
`Customers face template invalidation errors` where are you seeing the invalidation errors?  I'm trying to replicate with your template but not getting an error with `cfn-lint` or `aws cloudformation validate-template`

**Comment by razhamma** [comment]
I'm receiving error: "Template validation error: Given input did not match expected format" when upon trying to create stack via CFN console. Initial validation from designer goes through, however, attempt to create stack fails with above mentioned error.

**Comment by kddejong** [comment]
Perfect. Thank you!  Let me take a look

**Comment by cmmeyer** [comment]
Hi @razhamma -- I was able to use the template you provided without any errors in the linter and was also able to successfully generate a stack when I provided a valid parameter name and version.

The only way I could reproduce the error was to include bad characters in the parameter:
`ParameterName | bob@`

This triggered the following error:
`Incorrect format is used in the following SSM reference: [{{resolve:ssm:bob@:1.0}}]`

Is it possible this is what you are seeing? We do not validate inputs for parameters, but it might be possible to resolve this via an AllowedPattern on the ParameterName field...

**Comment by razhamma** [comment]
Hi @cmmeyer, yes the issue was due to one of the invalid parameter values and using `AllowedPattern` on the ParameterName field will surely help. Thanks.
However, during further testing on my side, discovered that:
- When we initiate `create-stack` operation, SSM dynamic reference's existence is determined by `GetParameters` API call to `ssm.amazonaws.com` service before CloudFormation starts stack creation - so not possible to use `AWS::SSM:Parameter` resource inside a stack and reference its value in dynamic referencing for SSM parameter under some other resource specification. 
- In other words, SSM parameter should already be available in order to be referenced under SSM dynamic reference string. Multiple stack updates is a solution in this case. 

Nothing from `cfn-python-lint`, it is something need to be addressed by service team.

In case, anyone interested in the flow mentioned above, here's the template:

```
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SSMParamName:
    Type: String
    Description: testing value for SSM
Resources:
  SSMParam:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Type: String
      Value: testValue
      Name: !Ref SSMParamName
  S3bucket:
    DependsOn: SSMParam
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join 
        - ''
        - - '{'
          - '{'
          - 'resolve:'
          - 'ssm:'
          - !Ref SSMParamName
          - ':'
          - '1'
          - '}'
          - '}'

```
