### ISSUE TITLE
cfn-lint fails to handle resource based meta-data for ignore_checks

### ISSUE THREAD

**Issue by xbalajipge** [aws-cloudformation/cfn-python-lint#867]
*cfn-lint version: (`cfn-lint --version`)*  cfn-lint 0.19.1

*Description of issue.*
Resource based meta-data to ignore_checks for errors and warnings doesn't work

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
  * If present, please add links to the (official) documentation for clarification.
  * Validate if the issue still exists with the latest version of `cfn-lint` and/or the latest Spec files
```
  rInstanceRole:
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3005
    Type: AWS::IAM::Role
    DependsOn: rInstancePolicy
    ManagedPolicyArns:
      - !Ref rInstancePolicy
```
another case:

```
  rMyRole:
    Type: "AWS::IAM::Role"
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3001
    Description: "Role description"
```

Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)
