### ISSUE TITLE
Condition !Equals function does not support !Select or !Join as arguments

### ISSUE THREAD

**Issue by phene** [aws-cloudformation/cfn-python-lint#881]
*cfn-lint version: 0.20.0*

Example valid CF template chunk:

```yaml
Parameters:
  SomeList:
    Type: CommaDelimitedList

Conditions:
  ListStartsWithFoo: !Equals [ !Select [ 0, !Ref SomeList ], Foo ]  
```

Fails with `E8003 Fn::Equals element must be a string, Ref, or a Fn::FindInMap`. It should accept any intrinsic function that results in a string, including `!Select` and`!Join`.
