### ISSUE TITLE
{{resolve:ssm:[a-zA-Z0-9_.-/]+:\\d+}} is not respected in allowed values checks

### ISSUE THREAD

**Issue by kisst** [aws-cloudformation/cfn-python-lint#894]
*cfn-lint version: (`cfn-lint --version`)*
0.20.1

*Description of issue.*
The following snippet is a valid CFN code, however it's marked as invalid, as it does not match the **REGEX_CIDR** nor other know data propagation methods like Functions
```
  SecurityGroupRule:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref SecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: '{{resolve:ssm:mysubnet}}'
```
See related docs https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html
