### ISSUE TITLE
cfn-lint shows `W1020 Fn::Sub isn't needed` on Serverless LayerVersion property LayerName when a Variable is actually present

### ISSUE THREAD

**Issue by patrickgreenwell** [aws-cloudformation/cfn-python-lint#897]
*cfn-lint version: 0.20.1*

cfn-lint shows `W1020 Fn::Sub isn't needed` on Serverless LayerVersion property LayerName when a Variable is actually present in the layerName String of the intrinsic function Sub

Please provide as much information as possible:

sample resource: 
```yaml
APICommonCodeLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      Description: API common libraries
      LayerName: 
        Fn::Sub: 'api-common-code-layer-${Environment}'
      ContentUri: api/common
      CompatibleRuntimes:
        - nodejs8.10
      RetentionPolicy: Retain
```
Where Environment is a Paramater with the following definition:

```yaml
Environment:
    AllowedValues:
      - Dev
      - Qa
      - Staging
      - Mirror
      - Prod
    ConstraintDescription: You must specify a valid EnvironmentValue
    Default: Dev
    Description: Environment for to Deploy to
    Type: String
```
This only seems to affect LayerVersions as other resources proceed to not return the warning when using Fn::Sub in their names, even other AWS::Serverless resources.

Sample Template:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: SampleTemplate
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - Dev
      - Qa
      - Staging
      - Mirror
      - Prod
    ConstraintDescription: You must specify a valid EnvironmentValue
    Default: Dev
    Description: Environment for to Deploy to
Resources:
  APICommonCodeLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      Description: API common libraries
      LayerName: 
        Fn::Sub: 'api-common-code-layer-${Environment}'
      ContentUri: api/common
      CompatibleRuntimes:
        - nodejs8.10
      RetentionPolicy: Retain
```
