### ISSUE TITLE
Not recognizing '*' in a domain name in Route53 record set.

### ISSUE THREAD

**Issue by nsecws** [aws-cloudformation/cfn-python-lint#906]
cfn-lint version: 0.20.2 (latest version at time of writing)

Description of issue:
Is not recognizing valid Route53 use of * in a recordset. The record set deploys and works correctly. Sample code seen below.

```
Resources:
  startest30prdnuskinioRoute53pubRecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties: 
      Comment: '*.test30 prod'
      HostedZoneId: !Ref PrdNuskinIoPublicZone 
      RecordSets:
      - Name: '*.test30.prd.nuskin.io.'
        SetIdentifier: 'usw2'
        ResourceRecords:
          - '*.test30.prd.usw2.nuskin.io.'   <------ gives "does not contain a valid domain name" error
        TTL: '300'
        Type: CNAME
        Weight: 100
```
