### ISSUE TITLE
E2503 Security groups are not supported for load balancers with type "network"

### ISSUE THREAD

**Issue by eschneider1271** [aws-cloudformation/cfn-python-lint#922]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.21.0

*Description of issue.*
Here's a simplified version of our ALB template which reproduces the failure:
```
---
AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W2507 # AWS-Specific parameter types do not allow empty defaults

Parameters:
  Type:
    Type: String
    AllowedValues: ['application', 'network']
    Default: application
    Description: ALB type
  SecurityGroup:
    Type: CommaDelimitedList
    Description: Security group(s) for ALB
    Default: ''
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnets to use for ALB


Conditions:
  IsTypeNetwork: !Equals [!Ref Type, 'network']

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: 1.2.3.4
      Name: MyName
      Scheme: internet-facing
      SecurityGroups: !If
        - IsTypeNetwork
        - !Ref 'AWS::NoValue'
        - !Ref SecurityGroup
      Subnets: !Ref Subnets
      Type: !Ref Type
```

Here's the failure:
```
$ cfn-lint stacks/test-alb.template
E2503 Security groups are not supported for load balancers with type "network"
stacks/test-alb.template:36:7
```

This had been linting fine up until today (no recent changes to the template), so I think it may been introduced in the latest release: https://github.com/aws-cloudformation/cfn-python-lint/blob/master/CHANGELOG.md#0210
