### ISSUE TITLE
Add support for AWS Backup resources

### ISSUE THREAD

**Issue by paulwilljones** [aws-cloudformation/cfn-python-lint#941]
*cfn-lint version: (`cfn-lint --version`)* 0.21.3

*Description of issue.*
AWS::Backup resources are not supported for linting with CloudFormation templates.
I realise they are absent from the cfn-resource-specification, but capturing the issue for tracking their addition.

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
```
  BackupVaultWithDailyBackups:
    Type: "AWS::Backup::BackupVault"
    Properties:
      BackupVaultName: !Ref BackupVaultName
      EncryptionKeyArn: !GetAtt KMSKey.Arn

  TagBasedBackupSelection:
    Type: "AWS::Backup::BackupSelection"
    Properties:
      BackupSelection:
        SelectionName: "TagBasedBackupSelection"
        IamRoleArn: !GetAtt BackupRole.Arn
        ListOfTags:
         -
           ConditionType: "STRINGEQUALS"
           ConditionKey: "backup"
           ConditionValue: "daily"
      BackupPlanId: !Ref BackupPlanWithDailyBackups
```

```
E3001 Invalid or unsupported Type AWS::Backup::BackupSelection for resource TagBasedBackupSelection in eu-west-1
infrastructure/cloudformation/main.yml:20:5
E3001 Invalid or unsupported Type AWS::Backup::BackupVault for resource BackupVaultWithDailyBackups in eu-west-1
infrastructure/cloudformation/main.yml:37:5
```
  * If present, please add links to the (official) documentation for clarification.
  * Validate if the issue still exists with the latest version of `cfn-lint` and/or the latest Spec files
```
$ cfn-lint -u
$ cfn-lint --version
$ cfn-lint 0.21.3
```
