### ISSUE TITLE
cfn-lint complains about ARN reference

### ISSUE THREAD

**Issue by lvthillo** [aws-cloudformation/cfn-python-lint#950]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.21.4

*Description of issue.*
In a launch configuration we can reference the name OR Arn of an instance profile:
[doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html#cfn-as-launchconfig-iaminstanceprofile):

> IamInstanceProfile
> 
>     Provides the name or the Amazon Resource Name (ARN) of the instance profile associated with the IAM role for the instance. The instance profile contains the IAM role. 

Using `!Ref` to get the name of the instance profile works well but cfn-lint complains when I use  `!GetAtt `to get the Arn

Part of Stack:
```
Resources:
  ASGLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: t2.micro
      KeyName: !Ref SSHKey
      LaunchConfigurationName: ASGLaunchConfiguration
      IamInstanceProfile: !Ref ASGInstanceProfile
```

No errors above for `cfn-lint`, but it complains when I use:
```
Resources:
  ASGLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: t2.micro
      KeyName: !Ref SSHKey
      LaunchConfigurationName: ASGLaunchConfiguration
      IamInstanceProfile: !GetAtt ASGInstanceProfile.Arn
```

Error:
```
cfn-lint -t template.yml
E3008 Property "IamInstanceProfile" has no valid Fn::GetAtt options at Resources/ASGLaunchConfiguration/Properties/IamInstanceProfile/Fn::GetAtt
template.yml:50:7
```

Stack creation goes well and everything works as expected.
