### ISSUE TITLE
Outside of an Sub error for arn:aws:s3:::${transfer:HomeBucket}

### ISSUE THREAD

**Issue by melcloud** [aws-cloudformation/cfn-python-lint#964]
*cfn-lint version:  0.21.5*

*Description of issue.*
When defining a scope down policy for AWS SFTP transfer, cfn-lint gives error **E1029 Found an embedded parameter outside of an "Fn::Sub"** on things like `arn:aws:s3:::${transfer:HomeBucket}`. Is there anyway to exclude those?

```yaml
  SftpScopeDownPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for restricting SFTP users to have access to only their home directory
      ManagedPolicyName: sftp-scope-down-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: AllowListingOfUserFolder
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource: arn:aws:s3:::${transfer:HomeBucket}
            Condition:
              StringLike:
                s3:prefix:
                  - '${transfer:HomeFolder}'
                  - '${transfer:HomeFolder}/*'
          -
            Sid: HomeDirectoryObjectAccess
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:PutObject
              - s3:DeleteObject
              - s3:DeleteObjectVersion
              - s3:GetObjectACL
            Resource: arn:aws:s3:::${transfer:HomeDirectory}*
```
