### ISSUE TITLE
Specification bug(s) LaunchTemplates

### ISSUE THREAD

**Issue by fatbasstard** [aws-cloudformation/cfn-python-lint#975]
Working on changing from `LaunchConfiguration` to `LaunchTemplate` and hitting some issues.

PR is coming soon with improvements for the linter, creating this issue to keep track of Spec bugs.

**TagSpecification**

Template:
```
...
        TagSpecifications:
          - Tags:
            - Key: "Name"
              Value: "my-launchTemplate"
```
Is OK according to the specs and [documentation]( https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-tagspecification.html)

Error:
```The resource type cannot be null or empty. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidTagSpecification.Malformed; Request ID: 5fbeae6a-d07f-4261-8eb6-e68e3e7fab1f)```

Solution:
Apparantly `ResourceType` is mandatory

Same for Tags:

```
The tags cannot be null or empty. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidTagSpecification.Malformed; Request ID: e70fb87b-943c-41c2-9727-1bd8745ee7c1)
```

Doublechecked if Stack tagging might be the "workaround" for this, but it gives the same errors then 😋
