### ISSUE TITLE
E800x rules need Fn::Contains and others

### ISSUE THREAD

**Issue by kgutwin** [aws-cloudformation/cfn-python-lint#979]
*cfn-lint version: 0.21.4*

I appreciate the new E800x rules, but they're failing on my template that has Cloudformation Constraint Rules in it: https://aws.amazon.com/blogs/mt/how-to-perform-cross-parameter-validation-using-aws-cloudformation-rules-and-assertions/

The `Rules:` block in a CloudFormation template is poorly documented, but the following template launches just fine for me:

```
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Users:
    Type: CommaDelimitedList
Rules:
  AtLeastOneUserSpecified:
    Assertions:
      - Assert: !Not [!Contains [!Ref Users, ""]]
        AssertDescription: Must specify at least one user
Resources:
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      Tags:
        - Key: BucketUsers
          Value: !Join [":", !Ref Users]
```

If you leave the Users parameter empty, the template will fail to launch because the Assertion fails.

These rules are derived from Service Catalog, so all of the intrinsic functions supported by Service Catalog (https://docs.aws.amazon.com/servicecatalog/latest/adminguide/reference-template_constraint_rules.html) should also be allowed by the E800x tests:

* Fn::And
* Fn::Contains
* Fn::EachMemberEquals
* Fn::EachMemberIn
* Fn::Equals
* Fn::If
* Fn::Not
* Fn::Or
* Fn::RefAll
* Fn::ValueOf
* Fn::ValueOfAll

Cross-reference: #854 #874 #876
